// Types
export default Object.freeze({
    PRODUCTS_FILL:                 'PRODUCTS_FILL',
    PRODUCTS_FETCH_ASYNC:          'PRODUCTS_FETCH_ASYNC',
    CREATE_NEW_PRODUCT_ASYNC:      'CREATE_NEW_PRODUCT_ASYNC',
    CREATE_NEW_PRODUCT_SYNC:       'CREATE_NEW_PRODUCT_SYNC',
    EDIT_PRODUCT_ASYNC:            'EDIT_PRODUCT_ASYNC',
    EDIT_PRODUCT_SYNC:             'EDIT_PRODUCT_SYNC',
    DELETE_PRODUCT_ASYNC:          'DELETE_PRODUCT_ASYNC',
    DELETE_PRODUCT_SYNC:           'DELETE_PRODUCT_SYNC',
    INCREMENT_PRODUCT_VIEWS_ASYNC: 'INCREMENT_PRODUCT_VIEWS_ASYNC',
});
