export default Object.freeze({
    FETCH_GALLERY_ASYNC:       'FETCH_GALLERY_ASYNC',
    GALLERY_FILL:              'GALLERY_FILL',
    UPDATE_GALLERY_ASYNC:      'UPDATE_GALLERY_ASYNC',
    UPDATE_GALLERY_SYNC:       'UPDATE_GALLERY_SYNC',
    DELETE_GALLERY_ITEM_ASYNC: 'DELETE_GALLERY_ITEM_ASYNC',
    DELETE_GALLERY_ITEM_SYNC:  'DELETE_GALLERY_ITEM_SYNC',
});
