export default Object.freeze({
    SET_PRODUCTS_FILTER_STATE:         'SET_PRODUCTS_FILTER_STATE',
    SET_CART_MODAL_STATE:              'SET_CART_MODAL_STATE',
    SET_VIEWED_PRODUCTS_STATE:         'SET_VIEWED_PRODUCTS_STATE',
    SET_INITIAL_VIEWED_PRODUCTS_STATE: 'SET_INITIAL_VIEWED_PRODUCTS_STATE',
    RESET_TO_INNITIAL_STATE:           'RESET_TO_INNITIAL_STATE',
});
