export default Object.freeze({
    FETCH_ORDERS_ASYNC:      'FETCH_ORDERS_ASYNC',
    ORDERS_FILL:             'ORDERS_FILL',
    CREATE_ORDER_ASYNC:      'CREATE_ORDER_ASYNC',
    CREATE_ORDER_SYNC:       'CREATE_ORDER_SYNC',
    EDIT_ORDER_ASYNC:        'EDIT_ORDER_ASYNC',
    EDIT_ORDER_SYNC:         'EDIT_ORDER_SYNC',
    RESET_TO_INNITIAL_STATE: 'RESET_TO_INNITIAL_STATE',
});
